### PR TITLE
Organisation of files

### PR DESCRIPTION
**Pull request by pandafy**
In response to #3 

- Added solution of CATFEED in CPP
- Added link to question in markdown file
- Rearranged files

### CODE REVIEW

**Comment by pandafy** [comment]
@ekta1999 share your thoughts.

**Comment by darecoder** [comment]
1st year will not be able to do so much. I feel that making folder for each question and adding solutions in as many languages as possible is a good idea but question in markdown isn't working for me.

**Comment by pandafy** [comment]
How do you suggest referring to questions then?

**Comment by darecoder** [comment]
Simply add question link in comments.

**Comment by pandafy** [comment]
Then they won't be able to browse to it directly if question link is added in comments. In markdown, if they are using GitHub, they simply click on links.

i suggest doing both. :wink:

**Comment by darecoder** [comment]
Okay

**Pull request merged**
